apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resnext101.32x8d
  namespace: default
  labels:
    app: resnext101.32x8d
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${RESNEXT_101_32X8D_IMAGE}
