apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vgg16
  namespace: faas
  labels:
    app: vgg16
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${VGG_16_IMAGE}
