apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resnet101
  namespace: default
  labels:
    app: resnet101
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${RESNET_101_IMAGE}
