apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml

patches:
- target: 
     group: serving.knative.dev
     version: v1
     kind: Service
     name: resnext101.32x8d
  path: service-patch.yaml

