apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vgg11
  namespace: default
  labels:
    app: vgg11
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${VGG_11_IMAGE}
