apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wide-resnet101
  namespace: default
  labels:
    app: wide-resnet101
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${WIDE_RESNET101_IMAGE}
