apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: resnet152
  serviceType: faas
resources:
- service.yaml

patches:
- target: 
     group: serving.knative.dev
     version: v1
     kind: Service
     name: resnet152
  path: service-startup-probe-patch.yaml

