apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resnet152
  namespace: faas
  labels:
    app: resnet152
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${RESNET_152_IMAGE}
