apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: densenet201
  namespace: default
  labels:
    app: densenet201
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${DENSENET_201_IMAGE}
