apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: densenet121
  namespace: faas
  labels:
    app: densenet121
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${DENSENET_121_IMAGE}
