apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: squeezenet1.1
  serviceType: faas
resources:
- service.yaml

patches:
- target: 
     group: serving.knative.dev
     version: v1
     kind: Service
     name: squeezenet1.1
  path: service-patch.yaml

