apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vgg19
  namespace: default
  labels:
    app: vgg19
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${VGG_19_IMAGE}
