apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vgg16-bn
  namespace: faas
  labels:
    app: vgg16-bn
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${VGG_16_BN_IMAGE}
