apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: densenet161
  namespace: default
  labels:
    app: densenet161
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${DENSENET_161_IMAGE}
