apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: densenet169
  namespace: faas
  labels:
    app: densenet169
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${DENSENET_169_IMAGE}
