apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resnet18
  namespace: faas
  labels:
    app: resnet18
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${RESNET_18_IMAGE}
