apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resnet34
  namespace: default
  labels:
    app: resnet34
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${RESNET_34_IMAGE}
