apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resnet50
  namespace: faas
  labels:
    app: resnet50
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${RESNET_50_IMAGE}
