apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resnext101_32x8d
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/resnext101_32x8d
