apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: alexnet
  namespace: faas
  labels:
    app: alexnet
    serviceType: faas
spec:
  template:
    spec:
      containers:
      - image: ${ALEX_NET_IMAGE}
