apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wide_resnet101_2
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/wide_resnet101_2
