apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: resnext50_32x4d
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/resnext50_32x4d
